import { Exercise } from "@/types";

export const exercises: Exercise[] = [
  // Chest
  {
    id: "push-ups",
    name: "Push-ups",
    nameUk: "Віджимання",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps", "shoulders", "core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "close-grip-push-ups",
    name: "Close Grip Push-ups",
    nameUk: "Віджимання вузьким хватом",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "decline-push-ups",
    name: "Decline Push-ups",
    nameUk: "Віджимання з піднятими ногами",
    primaryMuscle: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "dips",
    name: "Dips",
    nameUk: "Віджимання на брусах",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "barbell-bench-press",
    name: "Barbell Bench Press",
    nameUk: "Жим штанги лежачи",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "dumbbell-bench-press",
    name: "Dumbbell Bench Press",
    nameUk: "Жим гантелей лежачи",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    nameUk: "Жим гантелей під кутом вгору",
    primaryMuscle: "chest",
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "decline-dumbbell-press",
    name: "Decline Dumbbell Press",
    nameUk: "Жим гантелей під кутом вниз",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "dumbbell-flyes",
    name: "Dumbbell Flyes",
    nameUk: "Розводка гантелей лежачи",
    primaryMuscle: "chest",
    secondaryMuscles: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "cable-crossover",
    name: "Cable Crossover",
    nameUk: "Розводка у кросовері",
    primaryMuscle: "chest",
    secondaryMuscles: ["shoulders"],
    equipment: ["cable"],
    difficulty: "intermediate",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "pec-deck",
    name: "Pec Deck",
    nameUk: "Пек-дек (тренажер-метелик)",
    primaryMuscle: "chest",
    secondaryMuscles: [],
    equipment: ["machine"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "dumbbell-pullover",
    name: "Dumbbell Pullover",
    nameUk: "Пуловер з гантеллю",
    primaryMuscle: "chest",
    secondaryMuscles: ["back"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },

  // Back
  {
    id: "wide-grip-pull-ups",
    name: "Wide Grip Pull-ups",
    nameUk: "Підтягування широким хватом",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps", "forearms"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "close-grip-pull-ups",
    name: "Close Grip Pull-ups",
    nameUk: "Підтягування вузьким хватом",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "chin-ups",
    name: "Chin-ups",
    nameUk: "Підтягування зворотним хватом",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "barbell-row",
    name: "Barbell Row",
    nameUk: "Тяга штанги в нахилі",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps", "forearms"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "dumbbell-row",
    name: "Dumbbell Row",
    nameUk: "Тяга гантелі в нахилі (одна рука)",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    type: "strength",
    isUnilateral: true,
  },
  {
    id: "two-dumbbell-row",
    name: "Two Dumbbell Row",
    nameUk: "Тяга двох гантелей",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "cable-row",
    name: "Cable Row",
    nameUk: "Тяга горизонтального блоку",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps"],
    equipment: ["cable"],
    difficulty: "beginner",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "lat-pulldown-wide",
    name: "Lat Pulldown Wide",
    nameUk: "Тяга верхнього блоку (широким хватом)",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps"],
    equipment: ["cable"],
    difficulty: "beginner",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "lat-pulldown-close",
    name: "Lat Pulldown Close",
    nameUk: "Тяга верхнього блоку (вузьким хватом)",
    primaryMuscle: "back",
    secondaryMuscles: ["biceps"],
    equipment: ["cable"],
    difficulty: "beginner",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "hyperextension",
    name: "Hyperextension",
    nameUk: "Гіперекстензія",
    primaryMuscle: "back",
    secondaryMuscles: ["hamstrings", "glutes"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "barbell-shrugs",
    name: "Barbell Shrugs",
    nameUk: "Шраги зі штангою",
    primaryMuscle: "back",
    secondaryMuscles: [],
    equipment: ["barbell"],
    difficulty: "beginner",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "dumbbell-shrugs",
    name: "Dumbbell Shrugs",
    nameUk: "Шраги з гантелями",
    primaryMuscle: "back",
    secondaryMuscles: [],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    type: "strength",
    isUnilateral: false,
  },

  // Shoulders
  {
    id: "dumbbell-shoulder-press-standing",
    name: "Dumbbell Shoulder Press Standing",
    nameUk: "Жим гантелей стоячи",
    primaryMuscle: "shoulders",
    secondaryMuscles: ["triceps"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "dumbbell-shoulder-press-seated",
    name: "Dumbbell Shoulder Press Seated",
    nameUk: "Жим гантелей сидячи",
    primaryMuscle: "shoulders",
    secondaryMuscles: ["triceps"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "military-press",
    name: "Military Press",
    nameUk: "Жим штанги армійський",
    primaryMuscle: "shoulders",
    secondaryMuscles: ["triceps", "core"],
    equipment: ["barbell"],
    difficulty: "advanced",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "lateral-raises",
    name: "Lateral Raises",
    nameUk: "Махи гантелями в сторони",
    primaryMuscle: "shoulders",
    secondaryMuscles: [],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "rear-delt-raises",
    name: "Rear Delt Raises",
    nameUk: "Махи в нахилі (задня дельта)",
    primaryMuscle: "shoulders",
    secondaryMuscles: [],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "front-raises",
    name: "Front Raises",
    nameUk: "Махи вперед",
    primaryMuscle: "shoulders",
    secondaryMuscles: [],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "upright-row",
    name: "Upright Row",
    nameUk: "Тяга штанги до підборіддя",
    primaryMuscle: "shoulders",
    secondaryMuscles: ["biceps"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "reverse-pec-deck",
    name: "Reverse Pec Deck",
    nameUk: "Обернена розводка в тренажері",
    primaryMuscle: "shoulders",
    secondaryMuscles: [],
    equipment: ["machine"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },

  // Biceps
  {
    id: "barbell-curl",
    name: "Barbell Curl",
    nameUk: "Підйом штанги на біцепс",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: ["barbell"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "dumbbell-curl-alternating",
    name: "Dumbbell Curl Alternating",
    nameUk: "Підйом гантелей по черзі",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: true,
  },
  {
    id: "dumbbell-curl-simultaneous",
    name: "Dumbbell Curl Simultaneous",
    nameUk: "Підйом гантелей разом",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "hammer-curls",
    name: "Hammer Curls",
    nameUk: "Молотки",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "concentration-curl",
    name: "Concentration Curl",
    nameUk: "Концентрований підйом",
    primaryMuscle: "biceps",
    secondaryMuscles: [],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: true,
  },
  {
    id: "cable-curl",
    name: "Cable Curl",
    nameUk: "Підйом на блоці",
    primaryMuscle: "biceps",
    secondaryMuscles: [],
    equipment: ["cable"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "preacher-curl",
    name: "Preacher Curl",
    nameUk: "Підйом на лаві Скотта",
    primaryMuscle: "biceps",
    secondaryMuscles: [],
    equipment: ["barbell", "machine"],
    difficulty: "intermediate",
    type: "isolation",
    isUnilateral: false,
  },

  // Triceps
  {
    id: "french-press-lying",
    name: "French Press Lying",
    nameUk: "Французький жим лежачи",
    primaryMuscle: "triceps",
    secondaryMuscles: [],
    equipment: ["barbell"],
    difficulty: "intermediate",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "french-press-seated",
    name: "French Press Seated",
    nameUk: "Французький жим сидячи",
    primaryMuscle: "triceps",
    secondaryMuscles: [],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "close-grip-bench-press",
    name: "Close Grip Bench Press",
    nameUk: "Віджимання вузьким хватом",
    primaryMuscle: "triceps",
    secondaryMuscles: ["chest"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "cable-pushdown-rope",
    name: "Cable Pushdown Rope",
    nameUk: "Розгинання на блоці (канат)",
    primaryMuscle: "triceps",
    secondaryMuscles: [],
    equipment: ["cable"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "cable-pushdown-straight",
    name: "Cable Pushdown Straight",
    nameUk: "Розгинання на блоці (пряма рукоять)",
    primaryMuscle: "triceps",
    secondaryMuscles: [],
    equipment: ["cable"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "overhead-dumbbell-extension",
    name: "Overhead Dumbbell Extension",
    nameUk: "Розгинання гантелі з-за голови",
    primaryMuscle: "triceps",
    secondaryMuscles: [],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "tricep-dips",
    name: "Tricep Dips",
    nameUk: "Віджимання на брусах (акцент трицепс)",
    primaryMuscle: "triceps",
    secondaryMuscles: ["chest", "shoulders"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "kickbacks",
    name: "Kickbacks",
    nameUk: "Кік-беки",
    primaryMuscle: "triceps",
    secondaryMuscles: [],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: true,
  },

  // Quadriceps
  {
    id: "barbell-squat",
    name: "Barbell Squat",
    nameUk: "Присідання зі штангою",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["glutes", "hamstrings", "core"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    nameUk: "Присідання гоблет",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["glutes"],
    equipment: ["dumbbells", "kettlebell"],
    difficulty: "beginner",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "front-squat",
    name: "Front Squat",
    nameUk: "Фронтальні присідання",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["core", "glutes"],
    equipment: ["barbell"],
    difficulty: "advanced",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "leg-press",
    name: "Leg Press",
    nameUk: "Жим ногами в тренажері",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["glutes"],
    equipment: ["machine"],
    difficulty: "beginner",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    nameUk: "Розгинання ніг у тренажері",
    primaryMuscle: "quadriceps",
    secondaryMuscles: [],
    equipment: ["machine"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "lunges-barbell",
    name: "Lunges Barbell",
    nameUk: "Випади зі штангою",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["glutes"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: true,
  },
  {
    id: "lunges-dumbbells",
    name: "Lunges Dumbbells",
    nameUk: "Випади з гантелями",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["glutes"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: true,
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    nameUk: "Болгарські присідання",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["glutes"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: true,
  },
  {
    id: "step-ups",
    name: "Step-ups",
    nameUk: "Степ-апи",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["glutes"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    type: "strength",
    isUnilateral: true,
  },

  // Hamstrings/Glutes
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    nameUk: "Румунська тяга",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes", "back"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "conventional-deadlift",
    name: "Conventional Deadlift",
    nameUk: "Станова тяга класична",
    primaryMuscle: "back",
    secondaryMuscles: ["hamstrings", "glutes", "forearms"],
    equipment: ["barbell"],
    difficulty: "advanced",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "sumo-deadlift",
    name: "Sumo Deadlift",
    nameUk: "Станова тяга сумо",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes", "quadriceps"],
    equipment: ["barbell"],
    difficulty: "advanced",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "lying-leg-curl",
    name: "Lying Leg Curl",
    nameUk: "Згинання ніг лежачи",
    primaryMuscle: "hamstrings",
    secondaryMuscles: [],
    equipment: ["machine"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "seated-leg-curl",
    name: "Seated Leg Curl",
    nameUk: "Згинання ніг сидячи",
    primaryMuscle: "hamstrings",
    secondaryMuscles: [],
    equipment: ["machine"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "glute-hyperextension",
    name: "Glute Hyperextension",
    nameUk: "Гіперекстензія на сідниці",
    primaryMuscle: "glutes",
    secondaryMuscles: ["hamstrings"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "hip-thrust",
    name: "Hip Thrust",
    nameUk: "Hip Thrust (сідничний міст) зі штангою",
    primaryMuscle: "glutes",
    secondaryMuscles: ["hamstrings"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    nameUk: "Ягодичний місток",
    primaryMuscle: "glutes",
    secondaryMuscles: ["hamstrings"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    type: "strength",
    isUnilateral: false,
  },

  // Calves
  {
    id: "standing-calf-raise",
    name: "Standing Calf Raise",
    nameUk: "Підйом на носки стоячи",
    primaryMuscle: "calves",
    secondaryMuscles: [],
    equipment: ["machine"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "seated-calf-raise",
    name: "Seated Calf Raise",
    nameUk: "Підйом на носки сидячи",
    primaryMuscle: "calves",
    secondaryMuscles: [],
    equipment: ["machine"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "calf-raise-machine",
    name: "Calf Raise Machine",
    nameUk: "Підйом на носки в тренажері (осел)",
    primaryMuscle: "calves",
    secondaryMuscles: [],
    equipment: ["machine"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },

  // Forearms
  {
    id: "wrist-curl",
    name: "Wrist Curl",
    nameUk: "Згинання зап'ястя зі штангою",
    primaryMuscle: "forearms",
    secondaryMuscles: [],
    equipment: ["barbell"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "reverse-wrist-curl",
    name: "Reverse Wrist Curl",
    nameUk: "Розгинання зап'ястя",
    primaryMuscle: "forearms",
    secondaryMuscles: [],
    equipment: ["barbell"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "farmers-walk",
    name: "Farmer's Walk",
    nameUk: "Утримання важкого хвата (farmer's walk)",
    primaryMuscle: "forearms",
    secondaryMuscles: ["core", "shoulders"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },

  // Core
  {
    id: "crunches",
    name: "Crunches",
    nameUk: "Прес класичний",
    primaryMuscle: "core",
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    nameUk: "Підйом ніг у висі",
    primaryMuscle: "core",
    secondaryMuscles: ["core"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "plank",
    name: "Plank",
    nameUk: "Планка",
    primaryMuscle: "core",
    secondaryMuscles: ["shoulders"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    type: "strength",
    isUnilateral: false,
  },
  {
    id: "side-plank",
    name: "Side Plank",
    nameUk: "Бокова планка",
    primaryMuscle: "core",
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    type: "strength",
    isUnilateral: true,
  },
  {
    id: "bicycle-crunches",
    name: "Bicycle Crunches",
    nameUk: "Велосипед",
    primaryMuscle: "core",
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "cable-crunches",
    name: "Cable Crunches",
    nameUk: "Скручування на блоці",
    primaryMuscle: "core",
    secondaryMuscles: [],
    equipment: ["cable"],
    difficulty: "beginner",
    type: "isolation",
    isUnilateral: false,
  },
  {
    id: "woodchops",
    name: "Woodchops",
    nameUk: "Дровосек з блоком",
    primaryMuscle: "core",
    secondaryMuscles: ["shoulders"],
    equipment: ["cable"],
    difficulty: "intermediate",
    type: "strength",
    isUnilateral: true,
  },
  {
    id: "ab-rollout",
    name: "Ab Rollout",
    nameUk: "Roll-out з колесом/штангою",
    primaryMuscle: "core",
    secondaryMuscles: ["shoulders"],
    equipment: ["bodyweight"],
    difficulty: "advanced",
    type: "strength",
    isUnilateral: false,
  },

  // Cardio
  {
    id: "running-treadmill",
    name: "Running (Treadmill)",
    nameUk: "Біг (доріжка)",
    primaryMuscle: "cardio",
    secondaryMuscles: ["quadriceps", "hamstrings"],
    equipment: ["machine"],
    difficulty: "beginner",
    type: "cardio",
    isUnilateral: false,
  },
  {
    id: "running-outdoor",
    name: "Running (Outdoor)",
    nameUk: "Біг (вулиця)",
    primaryMuscle: "cardio",
    secondaryMuscles: ["quadriceps", "hamstrings"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    type: "cardio",
    isUnilateral: false,
  },
  {
    id: "stationary-bike",
    name: "Stationary Bike",
    nameUk: "Велотренажер",
    primaryMuscle: "cardio",
    secondaryMuscles: ["quadriceps"],
    equipment: ["machine"],
    difficulty: "beginner",
    type: "cardio",
    isUnilateral: false,
  },
  {
    id: "rowing-machine",
    name: "Rowing Machine",
    nameUk: "Гребний тренажер",
    primaryMuscle: "cardio",
    secondaryMuscles: ["back", "quadriceps"],
    equipment: ["machine"],
    difficulty: "beginner",
    type: "cardio",
    isUnilateral: false,
  },
  {
    id: "jump-rope",
    name: "Jump Rope",
    nameUk: "Скакалка",
    primaryMuscle: "cardio",
    secondaryMuscles: ["calves"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    type: "cardio",
    isUnilateral: false,
  },
  {
    id: "burpees",
    name: "Burpees",
    nameUk: "Берпі",
    primaryMuscle: "cardio",
    secondaryMuscles: ["chest", "quadriceps", "core"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    type: "cardio",
    isUnilateral: false,
  },
  {
    id: "stair-climber",
    name: "Stair Climber",
    nameUk: "Підйом по сходах",
    primaryMuscle: "cardio",
    secondaryMuscles: ["glutes", "quadriceps"],
    equipment: ["machine"],
    difficulty: "beginner",
    type: "cardio",
    isUnilateral: false,
  },
  {
    id: "elliptical",
    name: "Elliptical",
    nameUk: "Еліптичний тренажер",
    primaryMuscle: "cardio",
    secondaryMuscles: ["quadriceps", "hamstrings"],
    equipment: ["machine"],
    difficulty: "beginner",
    type: "cardio",
    isUnilateral: false,
  },

  // Mobility
  {
    id: "hip-stretch",
    name: "Hip Stretch",
    nameUk: "Розтяжка стегна",
    primaryMuscle: "mobility",
    secondaryMuscles: ["hamstrings"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    type: "mobility",
    isUnilateral: true,
  },
  {
    id: "shoulder-stretch",
    name: "Shoulder Stretch",
    nameUk: "Розтяжка плечей",
    primaryMuscle: "mobility",
    secondaryMuscles: ["chest"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    type: "mobility",
    isUnilateral: true,
  },
  {
    id: "cat-cow",
    name: "Cat-Cow",
    nameUk: "Котяча спина",
    primaryMuscle: "mobility",
    secondaryMuscles: ["core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    type: "mobility",
    isUnilateral: false,
  },
  {
    id: "chest-stretch",
    name: "Chest Stretch",
    nameUk: "Розтяжка грудних",
    primaryMuscle: "mobility",
    secondaryMuscles: ["shoulders"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    type: "mobility",
    isUnilateral: false,
  },
  {
    id: "dynamic-warmup",
    name: "Dynamic Warm-up",
    nameUk: "Динамічна розминка суглобів",
    primaryMuscle: "mobility",
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    type: "mobility",
    isUnilateral: false,
  },
];

export function getExercisesByMuscleGroup(muscleGroup: string): Exercise[] {
  return exercises.filter(
    (e) => e.primaryMuscle === muscleGroup || e.secondaryMuscles.includes(muscleGroup as any)
  );
}

export function getExercisesByEquipment(equipment: string): Exercise[] {
  return exercises.filter((e) => e.equipment.includes(equipment as any));
}

export function getExercisesByDifficulty(difficulty: string): Exercise[] {
  return exercises.filter((e) => e.difficulty === difficulty);
}

export function searchExercises(query: string): Exercise[] {
  const lowerQuery = query.toLowerCase();
  return exercises.filter(
    (e) =>
      e.name.toLowerCase().includes(lowerQuery) ||
      e.nameUk.toLowerCase().includes(lowerQuery) ||
      e.primaryMuscle.toLowerCase().includes(lowerQuery)
  );
}

export function filterExercises(
  muscleGroup?: string,
  equipment?: string,
  difficulty?: string
): Exercise[] {
  return exercises.filter((e) => {
    if (muscleGroup && e.primaryMuscle !== muscleGroup) return false;
    if (equipment && !e.equipment.includes(equipment as any)) return false;
    if (difficulty && e.difficulty !== difficulty) return false;
    return true;
  });
}
